log_file: calendar.log
log_level: debug
grpc_listen: localhost:50051

pg_dsn: "host=localhost port=6432 user=calendar password=supersecret dbname=calendardb"
amqp_dsn: "amqp://guest:guest@localhost:5672/"
